// Reads every <button> in the back-office source and reports what class it carries and what it
// says. Generated, never hand-maintained: a hand-written inventory is exactly the kind of summary
// that drifts from the code it describes, which is the problem this whole audit exists to fix.
//
//   node scripts/design-audit/collect-buttons.mjs            → JSON on stdout
//   node scripts/design-audit/collect-buttons.mjs --markdown  → the audit document
//
// The label is what a person actually reads on screen. Every {...} expression is stripped, and any
// fragment still holding code punctuation afterwards is dropped rather than printed — a leaked
// `setConfirmDiscard(false)}> Keep them` is worse than useless in a document meant for review.

import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const SOURCE_DIR = "src/back-office/src";

const BUTTON = /<button\b(.*?)>(.*?)<\/button>/gs;
const CLASS_NAME = /className="([^"]*)"/;
const ARIA_LABEL = /aria-label="([^"]*)"/;
const CODE_PUNCTUATION = /[{}()=><;]/;

/** The words a person reads on the button, or a marker for an icon-only / unreadable one. */
function visibleLabel(attributes, body) {
  let text = body.replace(/<[^>]+>/g, " ");
  let previous;
  do {
    previous = text;
    text = text.replace(/\{[^{}]*\}/g, " ");
  } while (previous !== text);

  text = text.split(/\s+/).filter(Boolean).join(" ");
  if (CODE_PUNCTUATION.test(text)) text = "";
  text = text.replace(/&amp;/g, "&").replace(/&apos;/g, "'").replace(/&quot;/g, '"').trim();

  if (text) return text;
  const aria = ARIA_LABEL.exec(attributes);
  return aria ? `[icon: ${aria[1]}]` : "[no visible text]";
}

export function collectButtons(sourceDir = SOURCE_DIR) {
  const buttons = [];
  for (const file of readdirSync(sourceDir).filter(name => name.endsWith(".tsx")).sort()) {
    const source = readFileSync(join(sourceDir, file), "utf8");
    for (const match of source.matchAll(BUTTON)) {
      const [, attributes, body] = match;
      const className = CLASS_NAME.exec(attributes)?.[1] ?? "";
      buttons.push({ file, className, label: visibleLabel(attributes, body).slice(0, 60) });
    }
  }
  return buttons;
}

function groupBy(items, key) {
  const groups = new Map();
  for (const item of items) {
    const value = key(item);
    if (!groups.has(value)) groups.set(value, []);
    groups.get(value).push(item);
  }
  return groups;
}

function markdown(buttons) {
  const styled = buttons.filter(b => b.className.trim());
  const unstyled = buttons.filter(b => !b.className.trim());
  const lines = [];

  lines.push("# Every button in the back-office", "");
  lines.push("**Generated by `scripts/design-audit/collect-buttons.mjs` — do not edit by hand.**",
    "Re-run it and commit the result; a hand-maintained list drifts from the code, which is the",
    "problem this audit exists to expose.", "");
  lines.push(`**${buttons.length} buttons.** ${styled.length} carry a styling class;`,
    `**${unstyled.length} carry none at all** and render as the plain browser default.`, "");
  lines.push("Why this file exists: a count is not reviewable. You cannot judge whether \"four kinds",
    "is right\" without seeing what is actually in each bucket.", "");
  lines.push("---", "");

  lines.push("## The classes in use", "");
  const byClass = groupBy(
    styled.flatMap(b => b.className.split(/\s+/).filter(Boolean).map(c => ({ ...b, one: c }))),
    b => b.one
  );
  for (const [className, uses] of [...byClass].sort((a, b) => b[1].length - a[1].length)) {
    lines.push(`### \`.${className}\` — ${uses.length} uses`, "");
    const seen = new Set();
    for (const use of uses) {
      if (seen.has(use.label)) continue;
      seen.add(use.label);
      if (seen.size > 8) break;
      lines.push(`- ${use.label} · \`${use.file}\``);
    }
    if (uses.length > seen.size) lines.push(`- *…and ${uses.length - seen.size} more*`);
    lines.push("");
  }

  lines.push("---", "");
  lines.push(`## The unstyled ones — all ${unstyled.length}`, "");
  lines.push("Not one kind of thing. Every kind of thing, united only by nobody having styled them.", "");
  for (const [file, uses] of [...groupBy(unstyled, b => b.file)].sort((a, b) => b[1].length - a[1].length)) {
    lines.push(`### \`${file}\` — ${uses.length}`, "");
    for (const use of uses) lines.push(`- ${use.label}`);
    lines.push("");
  }
  return lines.join("\n");
}

if (process.argv[1]?.endsWith("collect-buttons.mjs")) {
  const buttons = collectButtons();
  process.stdout.write(
    process.argv.includes("--markdown") ? markdown(buttons) : JSON.stringify(buttons, null, 2)
  );
}
