// Every interactive control in the back-office, read with the TypeScript compiler's own parser.
//
//   node scripts/design-audit/collect.mjs            → JSON on stdout
//   node scripts/design-audit/collect.mjs --markdown  → the audit document
//
// This replaces two earlier regex-based collectors. Regex cannot parse JSX reliably: attributes
// span lines, contain `>` inside quotes and braces, and `<input>` is void so it has no closing
// tag. Successive patterns undercounted inputs as 9, then 13, then 39, against a true 111 — and
// worse, each wrong number looked plausible. A real parse removes the guessing entirely.
//
// The rule this whole audit exists to serve: generate the evidence, never hand-write a summary of
// it. A hand-maintained list drifts from the code, which is the problem the design system is for.

import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { createRequire } from "node:module";

const ts = createRequire(import.meta.url)("../../src/back-office/node_modules/typescript");

const SOURCE_DIR = "src/back-office/src";

/** Elements that are controls on their own, plus the ARIA roles that make any element one. */
const CONTROL_TAGS = new Set(["button", "input", "textarea", "select"]);
const CONTROL_ROLES = new Set(["dialog", "menu", "switch", "combobox", "tab", "radiogroup", "listbox"]);

/** A literal attribute value, or null when it is an expression rather than a fixed string. */
function attribute(node, name) {
  for (const property of node.attributes.properties) {
    if (!ts.isJsxAttribute(property) || property.name.getText() !== name) continue;
    const value = property.initializer;
    if (!value) return "";
    if (ts.isStringLiteral(value)) return value.text;
    if (ts.isJsxExpression(value) && value.expression && ts.isStringLiteral(value.expression)) {
      return value.expression.text;
    }
    return null; // dynamic
  }
  return undefined;
}

/** The words a person actually reads, ignoring any interpolated expression. */
function visibleText(node) {
  if (!node.children) return "";
  const parts = [];
  const walk = children => {
    for (const child of children) {
      if (ts.isJsxText(child)) parts.push(child.text);
      else if (ts.isJsxElement(child)) walk(child.children);
    }
  };
  walk(node.children);
  return parts.join(" ").split(/\s+/).filter(Boolean).join(" ");
}

export function collect(sourceDir = SOURCE_DIR) {
  const controls = [];

  for (const file of readdirSync(sourceDir).filter(name => name.endsWith(".tsx")).sort()) {
    const source = ts.createSourceFile(
      file,
      readFileSync(join(sourceDir, file), "utf8"),
      ts.ScriptTarget.Latest,
      true,
      ts.ScriptKind.TSX
    );

    const visit = node => {
      const opening = ts.isJsxElement(node) ? node.openingElement
        : ts.isJsxSelfClosingElement(node) ? node : null;

      if (opening) {
        const tag = opening.tagName.getText();
        const role = attribute(opening, "role");
        if (CONTROL_TAGS.has(tag) || (role && CONTROL_ROLES.has(role))) {
          const className = attribute(opening, "className");
          const type = attribute(opening, "type");
          const aria = attribute(opening, "aria-label");
          const text = ts.isJsxElement(node) ? visibleText(node) : "";

          controls.push({
            file,
            kind: tag === "input" ? `input[${type || "text"}]`
              : CONTROL_TAGS.has(tag) ? tag
              : `role=${role}`,
            // null means the class is computed at runtime — genuinely different from having none.
            className: className === null ? "(dynamic)" : (className ?? ""),
            label: (text || (aria ? `[aria: ${aria}]` : aria === null ? "[aria: dynamic]" : "[unlabelled]")).slice(0, 60)
          });
        }
      }
      ts.forEachChild(node, visit);
    };

    visit(source);
  }

  return controls;
}

function groupBy(items, key) {
  const groups = new Map();
  for (const item of items) {
    const value = key(item);
    if (!groups.has(value)) groups.set(value, []);
    groups.get(value).push(item);
  }
  return groups;
}

function markdown(controls) {
  const lines = [];
  const buttons = controls.filter(c => c.kind === "button");

  lines.push("# Every control in the back-office", "");
  lines.push("**Generated by `scripts/design-audit/collect.mjs` — do not edit by hand.**",
    "Parsed with the TypeScript compiler, not pattern-matched, so the counts are exact.", "");
  lines.push(`**${controls.length} controls**, of which **${buttons.length} are buttons**.`, "");

  lines.push("## By kind", "", "| Control | Count | Styled | Dynamic class | No class |", "|---|---|---|---|---|");
  for (const [kind, items] of [...groupBy(controls, c => c.kind)].sort((a, b) => b[1].length - a[1].length)) {
    const dynamic = items.filter(i => i.className === "(dynamic)").length;
    const none = items.filter(i => i.className === "").length;
    lines.push(`| \`${kind}\` | ${items.length} | ${items.length - dynamic - none} | ${dynamic} | **${none}** |`);
  }
  lines.push("", "A control with no class renders as the browser default — which is how a destructive",
    "action ends up looking identical to a safe one.", "", "---", "");

  lines.push("## Every styling class in use", "");
  const styled = controls.filter(c => c.className && c.className !== "(dynamic)");
  const byClass = [...groupBy(
    styled.flatMap(c => c.className.split(/\s+/).filter(Boolean).map(one => ({ ...c, one }))),
    c => c.one
  )].sort((a, b) => b[1].length - a[1].length);

  lines.push("| Class | Uses | Kinds | Example |", "|---|---|---|---|");
  for (const [className, uses] of byClass) {
    const kinds = [...new Set(uses.map(u => u.kind))].join(", ");
    const example = uses.find(u => !u.label.startsWith("["))?.label ?? uses[0].label;
    lines.push(`| \`.${className}\` | ${uses.length} | ${kinds} | ${example} |`);
  }
  lines.push("", "---", "");

  lines.push("## Controls with no class at all", "");
  const bare = controls.filter(c => c.className === "");
  for (const [file, inFile] of [...groupBy(bare, c => c.file)].sort((a, b) => b[1].length - a[1].length)) {
    lines.push(`### \`${file}\` — ${inFile.length}`, "");
    for (const control of inFile) lines.push(`- \`${control.kind}\` · ${control.label}`);
    lines.push("");
  }
  return lines.join("\n");
}

if (process.argv[1]?.endsWith("collect.mjs")) {
  const controls = collect();
  process.stdout.write(
    process.argv.includes("--markdown") ? markdown(controls) : JSON.stringify(controls, null, 2)
  );
}
