import { useCallback, useEffect, useMemo, useState } from "react";
import { Search } from "lucide-react";
import { BackOfficeApiError, loadMenuAvailability, loadScreensShowing, loadShelf, setItemAvailability, type MenuAvailability, type MenuScreenShowing, type ShelfMenu } from "./api";
import type { BackOfficeConfiguration } from "./config";
import { availabilityImpactNotice, availabilityTime } from "./builderModel.mjs";
import type { DestructiveReviewRequest } from "./DestructiveReviewDialog";
import "./quick-update-board.css";

type Placement = Readonly<{ key:string; itemId:string; itemName:string; menuId:string; menuName:string; sectionId:string; sectionName:string; screenIds:string[] }>;

export default function QuickUpdateBoard({ configuration, accessToken, venueTimezone, review }: Readonly<{
  configuration: BackOfficeConfiguration; accessToken: string; venueTimezone: string;
  review: (request: DestructiveReviewRequest) => Promise<boolean>;
}>) {
  const [menus,setMenus]=useState<ShelfMenu[]|null>(null), [availability,setAvailability]=useState<MenuAvailability[]>([]), [screens,setScreens]=useState<MenuScreenShowing[]>([]);
  const [selectedSection,setSelectedSection]=useState<string|null>(null), [query,setQuery]=useState(""), [error,setError]=useState<string|null>(null), [notice,setNotice]=useState<string|null>(null), [busy,setBusy]=useState<string|null>(null);
  const refresh=useCallback(async()=>{try{const [m,a,s]=await Promise.all([loadShelf(configuration,accessToken),loadMenuAvailability(configuration,accessToken),loadScreensShowing(configuration,accessToken)]);setMenus(m.filter(x=>x.screenIds.length>0&&x.board));setAvailability(a);setScreens(s);setError(null)}catch(f){setError(f instanceof BackOfficeApiError?f.message:"Vennusign could not load the 86 board.")}},[configuration,accessToken]);
  useEffect(()=>{void refresh()},[refresh]);
  const placements=useMemo<Placement[]>(()=>(menus??[]).flatMap(menu=>(menu.board?.sections??[]).flatMap(section=>section.items.map(item=>({key:`${menu.menuId}:${section.sectionId}:${item.itemId}`,itemId:item.itemId,itemName:item.name?.trim()||"Unnamed item",menuId:menu.menuId,menuName:menu.name,sectionId:section.sectionId,sectionName:section.name?.trim()||"Untitled section",screenIds:menu.screenIds})))),[menus]);
  const unavailable=useMemo(()=>new Map(availability.map(x=>[x.itemId,x])),[availability]);
  const sections=useMemo(()=>(menus??[]).flatMap(menu=>(menu.board?.sections??[]).map(section=>({menuId:menu.menuId,menuName:menu.name,sectionId:section.sectionId,sectionName:section.name?.trim()||"Untitled section"}))),[menus]);
  useEffect(()=>{if(!selectedSection&&sections[0])setSelectedSection(`${sections[0].menuId}:${sections[0].sectionId}`)},[sections,selectedSection]);
  const selected=sections.find(x=>`${x.menuId}:${x.sectionId}`===selectedSection), search=query.trim().toLocaleLowerCase();
  const available=placements.filter(x=>unavailable.get(x.itemId)?.isAvailable!==false).filter(x=>search?`${x.itemName} ${x.menuName} ${x.sectionName}`.toLocaleLowerCase().includes(search):x.menuId===selected?.menuId&&x.sectionId===selected?.sectionId);
  const off=placements.filter(x=>unavailable.get(x.itemId)?.isAvailable===false), offItems=[...new Map(off.map(x=>[x.itemId,x])).values()];
  const sectionAvailable=placements.filter(x=>x.menuId===selected?.menuId&&x.sectionId===selected?.sectionId&&unavailable.get(x.itemId)?.isAvailable!==false).length;
  const change=async(item:Placement,isAvailable:boolean)=>{const all=placements.filter(x=>x.itemId===item.itemId), names=[...new Set(all.flatMap(x=>x.screenIds).map(id=>screens.find(s=>s.screenId===id)?.screenName).filter((x):x is string=>Boolean(x)))];const confirmed=await review({title:isAvailable?`Put ${item.itemName} back on sale?`:`86 ${item.itemName}?`,consequence:isAvailable?`This restores it everywhere it appears${names.length?` on ${names.join(", ")}`:""}.`:`Guests will see Sold out everywhere it appears${names.length?` on ${names.join(", ")}`:""}.`,confirmLabel:isAvailable?"Put back on sale":"86 item",tone:isAvailable?"caution":"danger"});if(!confirmed)return;setBusy(item.itemId);try{const result=await setItemAvailability(configuration,accessToken,item.itemId,isAvailable);setNotice(availabilityImpactNotice(result.name,isAvailable,result.screenIds,screens));await refresh()}catch(f){setNotice(f instanceof Error?f.message:"Nothing changed. Try again.")}finally{setBusy(null)}};
  if(menus===null)return <section className="quick-update-state" role="status">Loading the 86 board…</section>;
  if(error)return <section className="quick-update-state" role="alert"><p>{error}</p><button onClick={()=>void refresh()}>Try again</button></section>;
  if(!menus.length)return <section className="quick-update-state"><h1>Nothing is on the screens yet</h1><p>Publish and assign a menu before using the 86 board.</p></section>;
  return <section className="quick-update" data-testid="quick-update-board">
    <aside className="quick-update__rail"><p className="quick-update__rail-title">On the screens</p>{menus.map(menu=><div className="quick-update__menu" key={menu.menuId}><strong>{menu.name}</strong>{(menu.board?.sections??[]).map(section=>{const key=`${menu.menuId}:${section.sectionId}`, count=placements.filter(x=>x.menuId===menu.menuId&&x.sectionId===section.sectionId&&unavailable.get(x.itemId)?.isAvailable===false).length, on=placements.filter(x=>x.menuId===menu.menuId&&x.sectionId===section.sectionId&&unavailable.get(x.itemId)?.isAvailable!==false).length;return <button key={key} className={selectedSection===key?"active":""} onClick={()=>{setSelectedSection(key);setQuery("")}}><span>{section.name||"Untitled section"}</span><small className={count?"off":""}>{count?`${count} 86’d`:`${on} available`}</small></button>})}</div>)}<p className="quick-update__totals">{placements.filter(x=>unavailable.get(x.itemId)?.isAvailable!==false).length} items available<br/>{menus.length} {menus.length===1?"menu":"menus"} · {new Set(menus.flatMap(x=>x.screenIds)).size} screens</p></aside>
    <main className="quick-update__main"><header><div><p>{selected?.menuName}</p><h1>{selected?.sectionName}</h1><span>{sectionAvailable} available · {off.filter(x=>x.menuId===selected?.menuId&&x.sectionId===selected?.sectionId).length} 86’d, listed on the right</span></div><time>{new Intl.DateTimeFormat("en-US",{weekday:"long",month:"short",day:"numeric",timeZone:venueTimezone}).format(new Date())}</time></header><label className="quick-update__search"><Search size={17}/><span className="visually-hidden">Search every menu on the screens</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search every menu on the screens"/></label><p className="quick-update__instruction">Tap an item to 86 it — everywhere it is showing, on every screen named below it</p>{available.length?<div className="quick-update__grid">{available.map(item=>{const names=[...new Set(item.screenIds.map(id=>screens.find(s=>s.screenId===id)?.screenName).filter(Boolean))];return <button key={item.key} disabled={busy===item.itemId} onClick={()=>void change(item,false)}><strong>{item.itemName}</strong><span>{names.join(", ")||"Assigned screen"}{placements.filter(x=>x.itemId===item.itemId).length>1?" · also elsewhere":""}</span></button>})}</div>:<p className="quick-update__empty">{query?"No on-screen items match that search.":"Everything in this section is 86’d."}</p>}</main>
    <aside className="quick-update__off"><header><h2>86’d right now <span>{offItems.length}</span></h2><p>Across every menu, not just this section. Guests see these as Sold out.</p></header>{offItems.map(item=>{const fact=unavailable.get(item.itemId)!, itemPlaces=off.filter(x=>x.itemId===item.itemId), age=availabilityTime(fact.changedUtc,venueTimezone)??"", carried=age.startsWith("yesterday")||/^[A-Z][a-z]{2} /.test(age);return <article key={item.itemId}><div><strong>{item.itemName}</strong>{carried?<em>Carryover</em>:null}</div><p>{itemPlaces.map(x=>`${x.menuName} · ${x.sectionName}`).join(" — ")}</p><footer><span>Off {age}{fact.changedBy?` · ${fact.changedBy}`:""}</span><button disabled={busy===item.itemId} onClick={()=>void change(item,true)}>Back on sale</button></footer></article>})}{!offItems.length?<p className="quick-update__empty">Nothing is 86’d right now.</p>:null}{notice?<p className="quick-update__notice" role="status">{notice}</p>:null}</aside>
  </section>;
}
