<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.11" />
    <PackageReference Include="RepoDb.SqlServer" Version="1.13.14" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vennu.Core.Models\Vennu.Core.Models.csproj" />
  </ItemGroup>

</Project>
