CREATE TABLE dbo.Venues
(
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Venues PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(200) NOT NULL,
    Timezone NVARCHAR(100) NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    PrimaryLanguage NVARCHAR(10) NOT NULL,
    SecondaryLanguage NVARCHAR(10) NULL,
    CreatedUtc DATETIME2(7) NOT NULL CONSTRAINT DF_Venues_CreatedUtc DEFAULT SYSUTCDATETIME(),
    UpdatedUtc DATETIME2(7) NOT NULL CONSTRAINT DF_Venues_UpdatedUtc DEFAULT SYSUTCDATETIME()
);
GO
